// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Finanzas.Infrastructure.Data
{
    public partial class Asociaciones
    {
        public int IdAsociacion { get; set; }
        public int IdOriginante { get; set; }
        public int IdAsociado { get; set; }
        public DateTime Desde { get; set; }
        public DateTime Hasta { get; set; }

        public virtual Usuarios IdAsociadoNavigation { get; set; }
        public virtual Usuarios IdOriginanteNavigation { get; set; }
    }
}