// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Finanzas.Infrastructure.Data
{
    public partial class Cuentas
    {
        public Cuentas()
        {
            Movimientos = new HashSet<Movimientos>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; }
        public decimal SaldoInicial { get; set; }
        public byte Estado { get; set; }

        public virtual ICollection<Movimientos> Movimientos { get; set; }
    }
}