// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Finanzas.Infrastructure.Data
{
    public partial class Movimientos
    {
        public decimal Id { get; set; }
        public DateTime FechaMovimiento { get; set; }
        public int IdTransaccion { get; set; }
        public int IdCuenta { get; set; }
        public string Detalle { get; set; }
        public decimal Importe { get; set; }
        public bool EsContrasiento { get; set; }
        public DateTime FechaGrabacion { get; set; }
        public int? IdUsuario { get; set; }

        public virtual Cuentas IdCuentaNavigation { get; set; }
        public virtual Transacciones IdTransaccionNavigation { get; set; }
        public virtual Usuarios IdUsuarioNavigation { get; set; }
    }
}