// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Finanzas.Infrastructure.Data
{
    public partial class Transacciones
    {
        public Transacciones()
        {
            Movimientos = new HashSet<Movimientos>();
        }

        public int Id { get; set; }
        public int IdRubro { get; set; }
        public string Descripcion { get; set; }
        public bool EsDebito { get; set; }
        public byte Estado { get; set; }

        public virtual Rubros IdRubroNavigation { get; set; }
        public virtual ICollection<Movimientos> Movimientos { get; set; }
    }
}