// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Finanzas.Infrastructure.Data
{
    public partial class Usuarios
    {
        public Usuarios()
        {
            AsociacionesIdAsociadoNavigation = new HashSet<Asociaciones>();
            AsociacionesIdOriginanteNavigation = new HashSet<Asociaciones>();
            Movimientos = new HashSet<Movimientos>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Contraseña { get; set; }
        public DateTime FechaAlta { get; set; }
        public byte Estado { get; set; }
        public DateTime? FechaBaja { get; set; }
        public string NombreCompleto { get; set; }
        public bool? CambiarContraseña { get; set; }
        public string PathAvatar { get; set; }

        public virtual ICollection<Asociaciones> AsociacionesIdAsociadoNavigation { get; set; }
        public virtual ICollection<Asociaciones> AsociacionesIdOriginanteNavigation { get; set; }
        public virtual ICollection<Movimientos> Movimientos { get; set; }
    }
}