//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finanzas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public decimal Id { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public int IdTransaccion { get; set; }
        public int IdCuenta { get; set; }
        public decimal Importe { get; set; }
        public System.DateTime FechaGrabacion { get; set; }
        public bool EsContrasiento { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Transaccion Transaccion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
